# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Person name')),
                ('reviewer', models.CharField(max_length=200, verbose_name='Your name')),
                ('review_type', models.IntegerField(choices=[(0, 'Personal'), (1, 'Proffesional')], verbose_name='Review type')),
                ('text', models.TextField(max_length=200, verbose_name='Your impression')),
            ],
        ),
    ]
