# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_proffesionalreview_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalreview',
            name='Related_as',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='personalreview',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='proffesionalreview',
            name='Related_By',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='proffesionalreview',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
